WITH source_data AS (
  SELECT * FROM {{ source('RAW', 'BOX_OFFICE_V3') }}
),

deduped AS (
  SELECT *
  FROM source_data
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TMDB_ID
    ORDER BY
      RELEASE_DATE DESC NULLS LAST,
      TMDB_ID ASC
  ) = 1
)

SELECT
  TMDB_ID,
  IMDB_ID,
  TITLE,
  RELEASE_DATE,
  ORIGINAL_LANGUAGE,
  PRODUCTION_COUNTRIES,
  GENRES,
  PRODUCTION_BUDGET,
  DIRECTOR,
  ACTORS,
  MPAA,
  RELEASE_TYPE,
  RUNTIME,
  OVERVIEW,
  TAGLINE,
  KEYWORDS,
  PRODUCTION_COMPANY,
  RELEASE_YEAR,
  WORLDWIDE_GROSS,
  current_timestamp() AS loaded_at
FROM deduped
