WITH source_data AS (
  SELECT * FROM {{ source('RAW', 'BOX_OFFICE_V4') }}
),

deduped AS (
  SELECT *
  FROM source_data
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TMDB_ID
    ORDER BY
      RELEASE_DATE DESC NULLS LAST,
      TMDB_ID ASC
  ) = 1
)

SELECT
  TMDB_ID,
  IMDB_ID,
  TITLE,
  ORIGINAL_TITLE,
  STATUS,
  RELEASE_DATE,
  RELEASE_YEAR,
  ORIGINAL_LANGUAGE,
  PRODUCTION_COUNTRIES,
  SPOKEN_LANGUAGES,
  GENRES,
  PRODUCTION_BUDGET,
  PRODUCTION_BUDGET_ORIGINAL,
  PRODUCTION_BUDGET_SOURCE,
  PRODUCTION_BUDGET_WAS_MISSING,
  WIKIDATA_BUDGET_USD,
  WIKIDATA_ITEM,
  WIKIDATA_LABEL,
  WORLDWIDE_GROSS,
  RUNTIME,
  DIRECTOR,
  ACTORS,
  MPAA,
  OVERVIEW,
  TAGLINE,
  KEYWORDS,
  PRODUCTION_COMPANY,
  HOMEPAGE,
  POSTER_PATH,
  BACKDROP_PATH,
  ADULT,
  POPULARITY,
  VOTE_AVERAGE,
  VOTE_COUNT,
  POSTER_COUNT,
  BACKDROP_COUNT,
  VIDEO_COUNT,
  ALTERNATIVE_TITLE_COUNT,
  TRANSLATION_COUNT,
  RELEASE_YEAR_QUERY,
  DISCOVER_PAGE,
  FETCHED_AT,
  SOURCE_DATASET,
  COLLECTION_ID,
  COLLECTION_NAME,
  current_timestamp() AS loaded_at
FROM deduped
